# Generated by Django 5.2 on 2025-06-05 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=uuid.UUID('2e66223d-1046-4361-9276-7801dc8df561'), max_length=255, unique=True),
        ),
    ]
