version: '3.9'

name: ug_locator
services:
  db:
    image: postgis/postgis:latest
    container_name: db
    platform: linux/amd64
    environment:
      POSTGRES_USER: justine
      POSTGRES_PASSWORD: justine
      POSTGRES_DB: ug_locator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - communication_network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - 8000:8000
    env_file: ".env.development"

    volumes:
      - ./src:/app
    networks:
      - communication_network
    depends_on:
     - db

volumes:
  postgres_data:

networks:
  communication_network:
    driver: bridge