FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get install -y curl 

COPY --from=ghcr.io/astral-sh/uv:0.7.3 /uv /uvx /bin/
COPY requirements.prod.txt .

RUN uv pip install -r requirements.prod.txt --system
COPY src .