version: '3.9'

name: ug_locator_dev
services:
  database:
    image: postgis/postgis:latest
    container_name: database
    platform: linux/amd64
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=database
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    networks:
      - app_network
    depends_on: [database]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
    networks:
      - app_network
    depends_on: [backend]


volumes:
  db_data_dev:

networks:
  app_network:
    driver: bridge