version: '3.9'

name: ug_locator_prod
services:
  db_prod:
    image: postgis/postgis:latest
    container_name: db_prod
    platform: linux/amd64
    env_file: .env.production
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - communication_network_prod

  backend_prod:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_prod
    ports:
      - 9000:8000
    env_file: .env.production
    networks:
      - communication_network_prod
    depends_on:
     - db_prod

volumes:
  postgres_data_prod:

networks:
  communication_network_prod:
    driver: bridge