FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    libpq-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    && apt-get clean

RUN apt-get update \
    && apt-get install -y binutils

COPY --from=ghcr.io/astral-sh/uv:0.7.3 /uv /uvx /bin/
COPY requirements.txt .
COPY requirements.dev.txt .

RUN uv pip install -r requirements.dev.txt --system

COPY . .

EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]